site_name: Reasoning Models - Lab
site_url: https://microsoft.github.io/reasoningmodels-lab
site_author: Kapil Dhanger
site_description: >-
  Workshop on using Reasoning models with Azure AI Foundry

repo_name: dhangerkapil/reasoning-llms-workshop
repo_url: https://github.com/dhangerkapil/reasoning-llms-workshop.git

theme:
  name: material
  font:
    code: Roboto Mono
    text: Roboto
  language: en
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.expand
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.top
    - toc.follow
    - navigation.footer
    - content.code.copy
    - content.tabs.link

extra:
  generator: false

plugins:
  - search

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji
  - pymdownx.highlight:
      auto_title: true
      linenums: true
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Getting Started:
      - Overview: getting-started/index.md
      - Setup from GitHub: https://github.com/dhangerkapil/reasoning-llms-workshop#getting-started
  - Use Cases:
      - Overview: use-cases/index.md
      - Financial Services:
          - Credit Risk Assessment:
              - Overview: use-cases/credit-risk-assessment-and-management/index.md
              - Description: use-cases/credit-risk-assessment-and-management/README.md
              - Prompt: use-cases/credit-risk-assessment-and-management/prompt.md
              - Analysis: use-cases/credit-risk-assessment-and-management/analysis.md
          - Loan Agreement:
              - Overview: use-cases/loan-agreement/index.md
              - Description: use-cases/loan-agreement/README.md
              - Prompt: use-cases/loan-agreement/prompt.md
              - Analysis: use-cases/loan-agreement/analysis.md
          - Portfolio Optimization:
              - Overview: use-cases/portfolio-optimization/index.md
              - Description: use-cases/portfolio-optimization/README.md
              - Prompt: use-cases/portfolio-optimization/prompt.md
              - Analysis: use-cases/portfolio-optimization/analysis.md
      - Insurance:
          - Claims Processing:
              - Overview: use-cases/insurance-claims-processing/index.md
              - Description: use-cases/insurance-claims-processing/README.md
              - Prompt: use-cases/insurance-claims-processing/prompt.md
              - Analysis: use-cases/insurance-claims-processing/analysis.md
          - Insurance Plan:
              - Overview: use-cases/insurance-plan/index.md
              - Description: use-cases/insurance-plan/README.md
              - Prompt: use-cases/insurance-plan/prompt.md
              - Analysis: use-cases/insurance-plan/analysis.md
          - Risk Assessment:
              - Overview: use-cases/risk-assessment-for-underwriting-health-auto-life-property/index.md
              - Description: use-cases/risk-assessment-for-underwriting-health-auto-life-property/README.md
              - Prompt: use-cases/risk-assessment-for-underwriting-health-auto-life-property/prompt.md
              - Analysis: use-cases/risk-assessment-for-underwriting-health-auto-life-property/analysis.md
      - Business Analytics:
          - Customer Relationship:
              - Overview: use-cases/customer-relationship-management/index.md
              - Prompt: use-cases/customer-relationship-management/prompt.md
              - Analysis: use-cases/customer-relationship-management/analysis.md
          - Data Analysis:
              - Overview: use-cases/data-analysis/index.md
              - Prompt: use-cases/data-analysis/prompt.md
              - Analysis: use-cases/data-analysis/analysis.md
          - Market Sentiment:
              - Overview: use-cases/market-sentiment-and-volatility-forecasting/index.md
              - Prompt: use-cases/market-sentiment-and-volatility-forecasting/prompt.md
              - Analysis: use-cases/market-sentiment-and-volatility-forecasting/analysis.md
      - Risk Management:
          - Fraud Detection:
              - Overview: use-cases/fraud-detection-and-prevention/index.md
              - Prompt: use-cases/fraud-detection-and-prevention/prompt.md
              - Analysis: use-cases/fraud-detection-and-prevention/analysis.md
          - Underwriting Analysis:
              - Overview: use-cases/underwriting-analysis/index.md
              - Prompt: use-cases/underwriting-analysis/prompt.md
              - Analysis: use-cases/underwriting-analysis/analysis.md
